#!/bin/sh
docker run \
  -n=false \
  --dns-search=vc-a \
  --lxc-conf="lxc.network.type = veth" \
  --lxc-conf="lxc.network.ipv4 = 172.16.255.254/16" \
  --lxc-conf="lxc.network.ipv4.gateway = 172.16.255.253" \
  --lxc-conf="lxc.network.link = docker0" \
  --lxc-conf="lxc.network.name = eth0" \
  --lxc-conf="lxc.network.flags = up" \
  --hostname="login" \
  -v /cluster/vc-a:/cluster/ \
  -v /usr/local:/usr/local \
  -t -i controller:5000/login /bin/bash
