#!/bin/sh
docker run \
  --net=none \
  --lxc-conf="lxc.network.type = veth" \
  --lxc-conf="lxc.network.ipv4 = 172.17.255.253/16" \
  --lxc-conf="lxc.network.ipv4.gateway = 172.17.255.254" \
  --lxc-conf="lxc.network.link = docker0" \
  --lxc-conf="lxc.network.name = eth0" \
  --lxc-conf="lxc.network.flags = up" \
  -t -i centos /bin/bash 
