#!/bin/bash
sed -i /etc/yum.repos.d/CentOS-Base.repo -e 's/enabled=.*$/enabled=1/'
touch /etc/sysconfig/iptables
yum install -y http://rdo.fedorapeople.org/rdo-release.rpm
yum install -y openstack-packstack
cat /root/.ssh/id_rsa.pub > /root/.ssh/authorized_keys
export HOME=/root
mkdir -p /tmp/.ssh

echo $(date) > /var/log/install_openstack
service iptables start
echo >> /var/log/install_openstack
modprobe xt_tcpudp
modprobe ip_conntrack

lsmod >> /var/log/install_openstack
echo >> /var/log/install_openstack
env >> /var/log/install_openstack
echo >> /var/log/install_openstack

packstack --allinone >> /var/log/install_openstack 2>&1
