#!/bin/bash
#
#       /etc/rc.d/init.d/fast-compute
#
#       Daemon for fast compute containers.
#       
# chkconfig:   2345 95 95
# description: Daemon for fast-compute

### BEGIN INIT INFO
# Provides:       fast-compute
# Required-Start: $network docker
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop:  0 1 6
# Short-Description: start and stop fast-compute
# Description: Daemon for fast-compute
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

export prog=fast-compute
start() {
    # ClusterVision
    sleep 1
    
    # get the latest version of the image
    docker pull controller:5050/compute 

    # Determine the container name and IP address
    # IP=$(host $(hostname) | awk -F' ' '{print $4}')
    NAME=$(hostname | sed s/node/c/)
    
    # Determine in which virtual cluster this node is active
    for VC in vc-{a..l}; do
        if host $NAME.$VC; then break; fi
    done
    IP=$(host ${NAME}.${VC} | awk -F' ' '{print $4}')

    # Set the gateway address on the controller node.
    GW=$(echo $IP | awk -F'/' '{print $1}' | awk -F'.' '{print $1"."$2".255.250"}')
    ip addr add ${GW}/16 dev docker0

    # Just a few cleanup actions for development. Since we use --rm
    # (and -r in the general docker), this should not be necessary.
    if [ $(docker ps -q | wc -l) -ne 0 ]; then
       docker stop $(docker ps -q)
    fi
    if [ $(docker ps -aq | wc -l) -ne 0 ]; then
       docker rm $(docker ps -aq)
    fi

    # Start the container
    docker run \
       -n=false \
       --dns-search="${VC}" \
       --dns=10.141.255.254 \
       --lxc-conf="lxc.network.type = veth" \
       --lxc-conf="lxc.network.ipv4 = ${IP}/16" \
       --lxc-conf="lxc.network.ipv4.gateway = ${GW}" \
       --lxc-conf="lxc.network.link = docker0" \
       --lxc-conf="lxc.network.name = eth0" \
       --lxc-conf="lxc.network.flags = up" \
       --privileged \
       -v /dev/infiniband:/dev/infiniband \
       -v /usr/local:/usr/local \
       -v /root:/root \
       -v /cluster/${VC}:/cluster \
       --hostname=${NAME} \
       --name=${NAME}.${VC} \
       --rm -t controller:5050/compute &
}

stop() {
    echo -n $"Stopping $prog: "
    NAME=$(hostname | sed s/node/c/)
    for VC in vc-{a..l}; do
        if host ${NAME}.${VC}; then 
            docker stop ${NAME}.${VC}
        fi
    done
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    docker ps | grep vc
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac

exit $?
